### ISSUE TITLE
Clean up original Data

### ISSUE THREAD

**Issue by t1brunne** [mauricenaef/birthhood#10]
Some experiences have unmatched Birthplaces:

ZENTRALKLINIKUM AUGSBURG
Universitätsklinikum Mannheim
universitätsklinikum freiburg
Klinikum Mannheim
Kantonsspital Luzern
Geburtshaus Zürcher Oberland
Geburtshaus Hamburg

**Comment by mauricenaef** [comment]
Data cleaned up and corrected the misspelling.
