### ISSUE TITLE
User Experience List

### ISSUE THREAD

**Issue by t1brunne** [mauricenaef/birthhood#20]
- [x] Markup (list: date, score, birth_place, birth_name), add Button (see Search Component for styling)
- [x] styling
- [x] Blank slate
- [x] Route Guards => auf main page redirecten

**Comment by t1brunne** [comment]
a single score does not exist yet per birthexperience. should we add one? or one per category (u, etc.)? to be saved when we save the birthexperience

**Comment by mauricenaef** [comment]
User gets redirected if not logged in
