### ISSUE TITLE
Experience add Formular

### ISSUE THREAD

**Issue by t1brunne** [mauricenaef/birthhood#21]
- [x] Route Guards
- [x] styling

- [x] Error line 24 (uid of undefined) upon logout

- [x] Toaster

- [x] handle incorrect date format

- [x] Write User_id in Firestore-Function instead of Angular-Code. <= not possible as of now
https://stackoverflow.com/questions/46912161/getting-the-user-id-from-a-firestore-trigger-in-cloud-functions-for-firebase
- [x] Update Birthplace Score-Firestore-Function : include scores and Count
  
  
  

- [x] add loader (upon submit)
  

- [x] breadcrumb show progress

**Comment by mauricenaef** [comment]
minor issue with saved data / guards / validation, 
when filling out a form and refreshing after the first form, the input data is lost and the form can be continued to be filled out and submitted with the first form being empty.
