### ISSUE TITLE
Birthplace-Detail-Component

### ISSUE THREAD

**Issue by t1brunne** [mauricenaef/birthhood#29]
- [x] chart polar chart (Chart JS)
- [x]  google maps routing link
- [x] Anzahl entries
- [x] markup
- [x] styling
- [x] Image

- [x] blankslate: do not load Chart if no data is available

**Comment by t1brunne** [comment]
https://stackoverflow.com/questions/46328575/using-chart-js-on-angular-4

**Comment by mauricenaef** [comment]
Leaving the Chart empty if no data
